networks:
  default: ~
  hostmanager:
    external: true

services:
  php:
    build:
      context: .
      target: bebou_php_dev
    container_name: bebou-php
    env_file:
      - docker.env
      - docker.env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bebou-nginx.rule=Host(`bebou.localhost`)"
      - "traefik.http.routers.bebou-nginx.entryPoints=web,websecure"
      - "traefik.http.routers.bebou-nginx.tls=true"
    networks:
      - hostmanager
      - default
    volumes:
      - ./:/srv:rw,cached

      - ./.docker/config/bashrc:/home/appuser/.bashrc
      - ./.docker/config/bash_aliases:/home/appuser/.bash_aliases
      - ./.docker/data/history:/home/appuser/.bash_history

  redis:
    image: redis:8.2.2-alpine
    container_name: bebou-redis
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mailcatcher:
    image: axllent/mailpit
    container_name: bebou-mail
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bebou-mail.rule=Host(`bebou-mail.localhost`)"
      - "traefik.http.routers.bebou-mail.entryPoints=web,websecure"
      - "traefik.http.routers.bebou-mail.tls=true"
      - "traefik.http.services.bebou-mail.loadbalancer.server.port=8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - hostmanager
      - default

  localstack:
    image: localstack/localstack:latest
    container_name: bebou-localstack
    environment:
      - SERVICES=s3
      - PERSISTENCE=1
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/localstack:/etc/localstack/init/ready.d
    ports:
      - "4566:4566"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  redis: ~
  localstack: ~
