controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

security_controllers:
    resource:
        path: ../src/Security/Controller/
        namespace: App\Security\Controller
    type: attribute

dmc_finder_controller:
    resource:
        path: ../src/DmcFinder/Controller/
        namespace: App\DmcFinder\Controller
    type: attribute
